runtime: python311

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  PORT: "8080"
  # Add your Gemini API key here or use Secret Manager
  # GEMINI_API_KEY: "your_key_here"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
